[versions]
loom = "1.17-SNAPSHOT"

minecraft = "26.3-rc-1"

fabric_loader = "0.19.5"
fabric_api = "0.160.3+26.3"

malilib = "4cb96026bf"
itemscroller = "26.2-0.32.0"
tweakeroo = "26.2-0.29.1"
litematica = "26.2-0.28.1"
minihud = "26.2-0.40.1"

conditionalmixin = "0.6.4"
modmenu = "21.0.0-alpha.1"
clientarguments = "1.13.1"
libgui = "17.0.0+26.2"
jei = "29.5.0.26"

xray = "7847444"
commandbutton = "2.5.0"
xaerominimap="fabric-26.1.2-25.3.12"


[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric_loader" }
fabric_api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric_api" }

malilib = { group = "com.github.sakura-ryoko", name = "malilib", version.ref = "malilib" }
itemscroller = { group = "com.github.sakura-ryoko", name = "itemscroller", version.ref = "itemscroller" }
tweakeroo = { group = "com.github.sakura-ryoko", name = "tweakeroo", version.ref = "tweakeroo" }
litematica = { group = "com.github.sakura-ryoko", name = "litematica", version.ref = "litematica" }
minihud = { group = "com.github.sakura-ryoko", name = "minihud", version.ref = "minihud" }

conditionalmixin = { group = "me.fallenbreath", name = "conditional-mixin-fabric", version.ref = "conditionalmixin" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
clientarguments = { group = "dev.xpple", name = "clientarguments", version.ref = "clientarguments" }
libgui = { group = "io.github.cottonmc", name = "LibGui", version.ref = "libgui" }
jei_api = { group = "mezz.jei", name = "jei-26.1.2-fabric-api", version.ref = "jei" }

xray = { group = "curse.maven", name = "advanced-xray-fabric-edition-444663", version.ref = "xray" }
commandbutton = { group = "maven.modrinth", name = "command-gui-buttons", version.ref = "commandbutton" }
xaerominimap = { group = "maven.modrinth", name = "xaeros-minimap", version.ref = "xaerominimap" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
